const types = {
    NAMES_IS_LOADING:'NAMES_IS_LOADING',
    NAMES_HAS_ERROR:'NAMES_HAS_ERROR',
    NAMES_FETCH_DATA_SUCCESS:'NAMES_FETCH_DATA_SUCCESS',
    NAMES_REMOVE_NAME:'NAMES_REMOVE_NAME',
    NAMES_ITEM_REMOVED:'NAMES_ITEM_REMOVED',
    NAMES_DATA_ADDED:'NAMES_DATA_ADDED'
}

export default types